import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { motion } from 'framer-motion';
import { FiArrowLeft, FiCalendar, FiUser } from 'react-icons/fi';

const api = axios.create({ baseURL: '/api' });

export default function BeritaDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDetail = async () => {
      try {
        const res = await api.get(`/news/${id}`);
        setData(res.data);
      } catch (err) {
        console.error("Berita tidak ditemukan:", err);
        navigate('/'); // Redirect if not found
      } finally {
        setLoading(false);
      }
    };
    fetchDetail();
  }, [id, navigate]);

  if (loading) return (
    <div className="min-h-screen pt-40 flex justify-center items-center font-bold text-gray-500 bg-slate-50">
      <motion.div animate={{ rotate: 360, scale: [1, 1.2, 1] }} transition={{ repeat: Infinity, duration: 1.5 }} className="w-16 h-16 border-t-4 border-emerald-600 border-solid rounded-full" />
    </div>
  );

  if (!data) return null;

  return (
    <div className="min-h-screen bg-slate-50 pt-24 pb-20 font-sans">
      <div className="max-w-4xl mx-auto px-4">
        {/* Breadcrumb & Navigation */}
        <div className="mb-8 flex items-center gap-4">
          <button onClick={() => navigate(-1)} className="p-2 bg-white text-slate-500 hover:text-emerald-600 rounded-full shadow-sm hover:shadow transition-all group">
            <FiArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" />
          </button>
          <div className="text-sm font-semibold text-slate-500 flex gap-2 items-center">
            <Link to="/" className="hover:text-emerald-600 transition">Beranda</Link>
            <span>/</span>
            <span className="text-emerald-600">Berita</span>
          </div>
        </div>

        {/* Article Header */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-slate-100 mb-8">
          <div className="inline-block px-3 py-1 bg-emerald-100 text-emerald-700 font-bold text-xs uppercase tracking-widest rounded-full mb-6">
            Berita Terkini
          </div>
          <h1 className="text-3xl md:text-5xl font-black text-slate-900 leading-tight mb-6">
            {data.title}
          </h1>
          <div className="flex flex-wrap items-center gap-6 text-slate-500 text-sm font-medium border-b border-slate-100 pb-8">
            <div className="flex items-center gap-2">
              <FiCalendar className="text-emerald-500" size={16} />
              <span>{new Date(data.publishedAt).toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</span>
            </div>
            {data.author && (
              <div className="flex items-center gap-2">
                <FiUser className="text-emerald-500" size={16} />
                <span>Oleh: <span className="text-slate-800 font-bold">{data.author}</span></span>
              </div>
            )}
          </div>

          {/* Hero Image */}
          {data.imageUrl && (
            <div className="w-full mt-8 rounded-2xl overflow-hidden bg-slate-100">
              <img src={data.imageUrl} alt={data.title} className="w-full h-auto max-h-[500px] object-cover" />
            </div>
          )}

          {/* Article Content */}
          <div className="mt-10 prose prose-lg prose-emerald max-w-none text-slate-700">
            {/* Render HTML content generated by ReactQuill safely */}
            <div dangerouslySetInnerHTML={{ __html: data.content }} className="rich-text-content" />
          </div>
        </motion.div>
      </div>

      <style>{`
         .rich-text-content p { margin-bottom: 1.5em; line-height: 1.8; color: #334155; }
         .rich-text-content h1, .rich-text-content h2, .rich-text-content h3 { font-weight: 800; color: #0f172a; margin-top: 1.5em; margin-bottom: 0.5em; }
         .rich-text-content ul, .rich-text-content ol { padding-left: 1.5em; margin-bottom: 1.5em; list-style-position: outside; }
         .rich-text-content ul { list-style-type: disc; }
         .rich-text-content ol { list-style-type: decimal; }
         .rich-text-content li { margin-bottom: 0.5em; color: #334155; }
         .rich-text-content strong { color: #0f172a; font-weight: 700; }
         .rich-text-content a { color: #10b981; text-decoration: underline; font-weight: 600; }
      `}</style>
    </div>
  );
}
